### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [grothjef/bootstrap#1]
Hmm - it looks like this repository is actually empty. Did you forget to `git push origin master`?

**Comment by grothjef** [comment]
That's weird :/
I'll check it out

**Comment by grothjef** [comment]
https://github.com/grothjef/using-erb

I guess that's the one

Weird

**Comment by chrisvfritz** [comment]
I'll just give you a :+1: here then and give you notes for both projects on that repo.
